spring.application.name=blogger-box-backend
server.port=1234

spring.datasource.url=jdbc:postgresql://REPLACE_WITH_DB_HOST:REPLACE_ME_WITH_DB_PORT/REPLACE_ME_WITH_DB_NAME
spring.datasource.username=REPLACE_ME_WITH_DB_USERNAME
spring.datasource.password=REPLACE_ME_WITH_DB_PASSWORD
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true