spring.application.name=blogger-box-backend
server.port=1234

spring.datasource.url=jdbc:postgresql://aws-1-eu-west-3.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.hpdukybblxtvndikvmos
spring.datasource.password=MDPSUPABASE
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true